window.OW = window.OW || {};
OW.displacement = function (field) {
  const b = field.kids[0];
  const h = 0.02;
  const load = (field.energy || 0) + (field.matter || 0);
  const amp = field.parent.amp * (1 + 0.05 * (field.matter || 0));
  const sigma = field.parent.sigma;
  const c = (x, y) => amp * OW.wake(Math.hypot(x, y), sigma);
  const gx = (c(b.x + h, b.y) - c(b.x - h, b.y)) / (2 * h);
  const gy = (c(b.x, b.y + h) - c(b.x, b.y - h)) / (2 * h);
  const th = Math.atan2(b.y, b.x);
  if (field._th == null) field._th = th;
  let dth = th - field._th;
  if (dth > Math.PI) dth -= 2 * Math.PI;
  if (dth < -Math.PI) dth += 2 * Math.PI;
  field._th = th;
  field.V = c(b.x, b.y);
  field.slope = Math.hypot(gx, gy);
  field.point = (field.point || 0) + 0.01 * (field.matter || 0);
  field.path = dth / 0.03;
  field.fieldRate = 0.01 * load;
  return { V: field.V, slope: field.slope, point: field.point, path: field.path, field: field.fieldRate };
};
