from pathlib import Path
p=Path('Virtual_Breadboard/js/circuit.js')
s=p.read_text()
def rep(a,b):
    global s
    if a not in s: raise SystemExit('missing anchor '+a[:100])
    s=s.replace(a,b,1)
rep("      this._t = 0; // running sim clock (seconds), shared by every AC/MTJ source",
    "      this._lastDt = null; // previous accepted solve dt; required by variable-step Gear2/BDF2 history\n      this._t = 0; // running sim clock (seconds), shared by every AC/MTJ source")
rep("      const integrationMethod = solverOptions && solverOptions.integrationMethod ? String(solverOptions.integrationMethod).toLowerCase() : 'backward-euler';\n      if (!['backward-euler', 'trapezoidal', 'gear2'].includes(integrationMethod)) throw new Error(`unknown integrationMethod '${integrationMethod}'`);\n      this._t += dt;",
    "      const integrationMethod = solverOptions && solverOptions.integrationMethod ? String(solverOptions.integrationMethod).toLowerCase() : 'backward-euler';\n      if (!['backward-euler', 'trapezoidal', 'gear2'].includes(integrationMethod)) throw new Error(`unknown integrationMethod '${integrationMethod}'`);\n      const previousDt = this._lastDt;\n      this._t += dt;")
rep("            const useGear2 = integrationMethod === 'gear2' && hasPrev2;\n            const useTrap = integrationMethod === 'trapezoidal' && this._capCurrentState.has(c.id);\n            let idealG;\n            let historyCurrent;\n            if (useGear2) {\n              idealG = 3 * c.value / (2 * dtSafe);\n              const vPrev2 = this._capPrevState.get(c.id);\n              historyCurrent = c.value * (4 * vPrev - vPrev2) / (2 * dtSafe);",
    "            const useGear2 = integrationMethod === 'gear2' && hasPrev2 && previousDt > 0;\n            const useTrap = integrationMethod === 'trapezoidal' && this._capCurrentState.has(c.id);\n            let idealG;\n            let historyCurrent;\n            if (useGear2) {\n              const hp = previousDt;\n              const a0 = (2 * dtSafe + hp) / (dtSafe * (dtSafe + hp));\n              const a1 = -(dtSafe + hp) / (dtSafe * hp);\n              const a2 = dtSafe / (hp * (dtSafe + hp));\n              idealG = c.value * a0;\n              const vPrev2 = this._capPrevState.get(c.id);\n              historyCurrent = -c.value * (a1 * vPrev + a2 * vPrev2);")
rep("          const useGear2 = integrationMethod === 'gear2' && hasPrev2;\n          const useTrap = integrationMethod === 'trapezoidal' && this._indVoltageState.has(ind.id);\n          let Leq;\n          let historyRhs;\n          if (useGear2) {\n            Leq = 3 * L / (2 * dtSafe);\n            const iPrev2 = this._indPrevState.get(ind.id);\n            historyRhs = L * (-4 * iPrev + iPrev2) / (2 * dtSafe);",
    "          const useGear2 = integrationMethod === 'gear2' && hasPrev2 && previousDt > 0;\n          const useTrap = integrationMethod === 'trapezoidal' && this._indVoltageState.has(ind.id);\n          let Leq;\n          let historyRhs;\n          if (useGear2) {\n            const hp = previousDt;\n            const a0 = (2 * dtSafe + hp) / (dtSafe * (dtSafe + hp));\n            const a1 = -(dtSafe + hp) / (dtSafe * hp);\n            const a2 = dtSafe / (hp * (dtSafe + hp));\n            Leq = L * a0;\n            const iPrev2 = this._indPrevState.get(ind.id);\n            historyRhs = L * (a1 * iPrev + a2 * iPrev2);")
# second Gear formula in capacitor post-solve
rep("          const useGear2 = integrationMethod === 'gear2' && hasPrev2;\n          const useTrap = integrationMethod === 'trapezoidal' && this._capCurrentState.has(c.id);\n          let idealG, historyCurrent;\n          if (useGear2) {\n            idealG = 3 * c.value / (2 * dtSafe);\n            historyCurrent = c.value * (4 * vPrev - this._capPrevState.get(c.id)) / (2 * dtSafe);",
    "          const useGear2 = integrationMethod === 'gear2' && hasPrev2 && previousDt > 0;\n          const useTrap = integrationMethod === 'trapezoidal' && this._capCurrentState.has(c.id);\n          let idealG, historyCurrent;\n          if (useGear2) {\n            const hp = previousDt;\n            const a0 = (2 * dtSafe + hp) / (dtSafe * (dtSafe + hp));\n            const a1 = -(dtSafe + hp) / (dtSafe * hp);\n            const a2 = dtSafe / (hp * (dtSafe + hp));\n            idealG = c.value * a0;\n            historyCurrent = -c.value * (a1 * vPrev + a2 * this._capPrevState.get(c.id));")
# set last dt just before return
rep("      if (!solver.converged) {\n        warnings.push(`SOLVER FAILED: nonlinear solve did not converge in ${solver.iterations}/${solver.maxIterations} iterations (stateStable=${solver.stateStable}, residual=${solver.maxResidual}, tolerance=${solver.residualTolerance})`);\n      }\n      return { voltages, currents, warnings, solver,",
    "      if (!solver.converged) {\n        warnings.push(`SOLVER FAILED: nonlinear solve did not converge in ${solver.iterations}/${solver.maxIterations} iterations (stateStable=${solver.stateStable}, residual=${solver.maxResidual}, tolerance=${solver.residualTolerance})`);\n      }\n      this._lastDt = dt;\n      return { voltages, currents, warnings, solver,")
p.write_text(s)
