from pathlib import Path
p=Path('Virtual_Breadboard/js/circuit.js')
s=p.read_text()
def rep(a,b):
    global s
    if a not in s: raise SystemExit('missing anchor: '+a[:100])
    s=s.replace(a,b,1)
rep("      if (c.type === 'acsource') uf.find(acInternal(c));", "      if (c.type === 'acsource' || c.type === 'pwl' || c.type === 'pulse') uf.find(acInternal(c));")
rep("        case 'led': case 'diode': case 'acsource':\n          add(c.a, c.b);", "        case 'led': case 'diode': case 'acsource': case 'pwl': case 'pulse':\n          add(c.a, c.b);")
anchor="""  function wave(amplitude, freqHz, phaseDeg, t) {\n    return amplitude * Math.sin(2 * Math.PI * freqHz * t + (phaseDeg * Math.PI) / 180);\n  }\n"""
insert=anchor+"""\n  // SPICE-style repeatable transient source waveforms. PWL points are\n  // [timeSeconds, volts] pairs, linearly interpolated between breakpoints\n  // and held at the endpoint values outside the declared time range.\n  function pwlValue(points, t) {\n    const pts = (points || []).map((p) => [Number(p[0]), Number(p[1])])\n      .filter((p) => Number.isFinite(p[0]) && Number.isFinite(p[1]))\n      .sort((a,b) => a[0]-b[0]);\n    if (!pts.length) return 0;\n    if (t <= pts[0][0]) return pts[0][1];\n    for (let i=1;i<pts.length;i++) {\n      if (t <= pts[i][0]) {\n        const [t0,v0]=pts[i-1], [t1,v1]=pts[i];\n        if (t1 === t0) return v1;\n        const f=(t-t0)/(t1-t0);\n        return v0 + f*(v1-v0);\n      }\n    }\n    return pts[pts.length-1][1];\n  }\n\n  // PULSE(V1 V2 TD TR TF PW PER)-class waveform. Zero rise/fall values are\n  // treated as ideal edges. If period is omitted/non-positive, one pulse is\n  // emitted and the source returns to V1 permanently.\n  function pulseValue(c, t) {\n    const v1=Number(c.v1 != null ? c.v1 : c.low != null ? c.low : 0) || 0;\n    const v2=Number(c.v2 != null ? c.v2 : c.high != null ? c.high : c.value != null ? c.value : 1) || 0;\n    const td=Math.max(0, Number(c.delay != null ? c.delay : c.td) || 0);\n    const tr=Math.max(0, Number(c.rise != null ? c.rise : c.tr) || 0);\n    const tf=Math.max(0, Number(c.fall != null ? c.fall : c.tf) || 0);\n    const pw=Math.max(0, Number(c.width != null ? c.width : c.pw) || 0);\n    const per=Number(c.period != null ? c.period : c.per) || 0;\n    if (t < td) return v1;\n    let x=t-td;\n    if (per > 0) x = x % per;\n    else if (x > tr + pw + tf) return v1;\n    if (tr > 0 && x < tr) return v1 + (v2-v1)*(x/tr);\n    if (x < tr + pw) return v2;\n    if (tf > 0 && x < tr + pw + tf) return v2 + (v1-v2)*((x-tr-pw)/tf);\n    return v1;\n  }\n\n  function transientSourceValue(c, t) {\n    if (c.type === 'pwl') return pwlValue(c.points || c.pwl, t);\n    if (c.type === 'pulse') return pulseValue(c, t);\n    return wave(c.value, c.freq || 1, c.phase || 0, t);\n  }\n"""
rep(anchor,insert)
rep("      const acsources = components.filter((c) => c.type === 'acsource');", "      const acsources = components.filter((c) => c.type === 'acsource' || c.type === 'pwl' || c.type === 'pulse');")
rep("        if (c.type === 'acsource') touch(acInternal(c));", "        if (c.type === 'acsource' || c.type === 'pwl' || c.type === 'pulse') touch(acInternal(c));")
rep("          } else if (c.type === 'acsource') {", "          } else if (c.type === 'acsource' || c.type === 'pwl' || c.type === 'pulse') {")
rep("        // AC source: an ideal source like a battery, but its target value is\n        // the shared sim clock's sinusoid instead of a constant.", "        // Time-domain source: shared MNA/source-impedance primitive for sine,\n        // PWL, and PULSE waveforms; only the commanded voltage differs.")
rep("          b[row] += wave(ac.value, ac.freq || 1, ac.phase || 0, t);", "          b[row] += transientSourceValue(ac, t);")
rep("        } else if (c.type === 'acsource') {\n          I = acCurrent.get(c.id) || 0;", "        } else if (c.type === 'acsource' || c.type === 'pwl' || c.type === 'pulse') {\n          I = acCurrent.get(c.id) || 0;")
rep("    AC_RINT, MTJ_RINT, NMOS_PARTS, PMOS_PARTS, mosfetSpec", "    AC_RINT, MTJ_RINT, wave, pwlValue, pulseValue, transientSourceValue, NMOS_PARTS, PMOS_PARTS, mosfetSpec")
p.write_text(s)
