from pathlib import Path
p=Path('Virtual_Breadboard/js/circuit.js')
s=p.read_text()

def rep(a,b):
    global s
    if a not in s: raise SystemExit('missing anchor: '+a[:100])
    s=s.replace(a,b,1)

rep("      this._capState = new Map(); // component id -> voltage across it last frame\n      this._indState = new Map(); // component id -> current through it last frame",
    "      this._capState = new Map(); // component id -> ideal-C voltage last frame\n      this._capPrevState = new Map(); // component id -> ideal-C voltage one additional frame back (Gear2 history)\n      this._capCurrentState = new Map(); // component id -> ideal-C branch current last frame (trapezoidal history)\n      this._indState = new Map(); // component id -> current through it last frame\n      this._indPrevState = new Map(); // component id -> current one additional frame back (Gear2 history)\n      this._indVoltageState = new Map(); // component id -> ideal-L voltage last frame (trapezoidal history)")

rep("      const uf = buildTopologyUnionFind(components, wires);\n      this._t += dt;",
    "      const uf = buildTopologyUnionFind(components, wires);\n      const integrationMethod = solverOptions && solverOptions.integrationMethod ? String(solverOptions.integrationMethod).toLowerCase() : 'backward-euler';\n      if (!['backward-euler', 'trapezoidal', 'gear2'].includes(integrationMethod)) throw new Error(`unknown integrationMethod '${integrationMethod}'`);\n      this._t += dt;")

oldcap='''          } else if (c.type === 'capacitor') {\n            // real series ESR folds straight into the backward-Euler\n            // companion resistance (Rs + dt/C in series is still just one\n            // resistance), so this is the SAME Norton-source technique as\n            // an ideal cap, just with a real Rs added before inverting --\n            // vPrev here is the voltage across the ideal-C portion alone\n            // (see the state-update comment below for why that matters).\n            const esr = capacitorESR(c);\n            const gC = 1 / (esr + Math.max(dt, 1e-12) / c.value);\n            const vPrev = this._capState.has(c.id) ? this._capState.get(c.id) : capInitialV(c);\n            const i = gi(uf.find(c.a));\n            const j = gi(uf.find(c.b));\n            stampG(i, i, gC);\n            stampG(j, j, gC);\n            stampG(i, j, -gC);\n            stampG(j, i, -gC);\n            const Ieq = gC * vPrev;\n            stampI(i, Ieq);\n            stampI(j, -Ieq);\n'''
newcap='''          } else if (c.type === 'capacitor') {\n            // Selectable SPICE-style integration companion for the ideal C\n            // in series with the part's real ESR. Gear2 bootstraps with BE\n            // until a second voltage-history point exists.\n            const esr = capacitorESR(c);\n            const dtSafe = Math.max(dt, 1e-12);\n            const vPrev = this._capState.has(c.id) ? this._capState.get(c.id) : capInitialV(c);\n            const hasPrev2 = this._capPrevState.has(c.id);\n            const useGear2 = integrationMethod === 'gear2' && hasPrev2;\n            const useTrap = integrationMethod === 'trapezoidal' && this._capCurrentState.has(c.id);\n            let idealG;\n            let historyCurrent;\n            if (useGear2) {\n              idealG = 3 * c.value / (2 * dtSafe);\n              const vPrev2 = this._capPrevState.get(c.id);\n              historyCurrent = c.value * (4 * vPrev - vPrev2) / (2 * dtSafe);\n            } else if (useTrap) {\n              idealG = 2 * c.value / dtSafe;\n              historyCurrent = idealG * vPrev + (this._capCurrentState.get(c.id) || 0);\n            } else {\n              idealG = c.value / dtSafe;\n              historyCurrent = idealG * vPrev;\n            }\n            const denom = 1 + idealG * esr;\n            const gC = idealG / denom;\n            const Ieq = historyCurrent / denom;\n            const i = gi(uf.find(c.a));\n            const j = gi(uf.find(c.b));\n            stampG(i, i, gC);\n            stampG(j, j, gC);\n            stampG(i, j, -gC);\n            stampG(j, i, -gC);\n            stampI(i, Ieq);\n            stampI(j, -Ieq);\n'''
rep(oldcap,newcap)

oldind='''        // inductor: dual of the capacitor's backward-Euler model. Its own\n        // current is a state variable (can't be read off node voltages\n        // alone), so it gets an extra branch-current unknown like an ideal\n        // source: V(a) - V(b) - R*iL - (L/dt)*iL = -(L/dt)*iL_prev. The\n        // real winding DCR just adds straight into that same coefficient\n        // -- an inductor's coil is a resistor and an inductor in series,\n        // and backward-Euler already treats L as a resistance (L/dt) plus\n        // a series source, so R and L/dt simply add.\n        inductors.forEach((ind, k) => {\n          const row = rowInd(k);\n          const Ldt = Math.max(ind.value, 1e-9) / Math.max(dt, 1e-12);\n          const dcr = inductorDCR(ind.value);\n          const iPrev = this._indState.has(ind.id)\n            ? this._indState.get(ind.id)\n            : (Number.isFinite(Number(ind.initialCurrent)) ? Number(ind.initialCurrent) : 0);\n'''
newind='''        // inductor companion using the selected integration method. Gear2\n        // bootstraps with backward Euler until two current-history points\n        // exist; trapezoidal bootstraps until the prior ideal-L voltage is\n        // known. DCR remains a real series resistor in every method.\n        inductors.forEach((ind, k) => {\n          const row = rowInd(k);\n          const L = Math.max(ind.value, 1e-9);\n          const dtSafe = Math.max(dt, 1e-12);\n          const dcr = inductorDCR(ind.value);\n          const iPrev = this._indState.has(ind.id)\n            ? this._indState.get(ind.id)\n            : (Number.isFinite(Number(ind.initialCurrent)) ? Number(ind.initialCurrent) : 0);\n          const hasPrev2 = this._indPrevState.has(ind.id);\n          const useGear2 = integrationMethod === 'gear2' && hasPrev2;\n          const useTrap = integrationMethod === 'trapezoidal' && this._indVoltageState.has(ind.id);\n          let Leq;\n          let historyRhs;\n          if (useGear2) {\n            Leq = 3 * L / (2 * dtSafe);\n            const iPrev2 = this._indPrevState.get(ind.id);\n            historyRhs = L * (-4 * iPrev + iPrev2) / (2 * dtSafe);\n          } else if (useTrap) {\n            Leq = 2 * L / dtSafe;\n            historyRhs = -Leq * iPrev - (this._indVoltageState.get(ind.id) || 0);\n          } else {\n            Leq = L / dtSafe;\n            historyRhs = -Leq * iPrev;\n          }\n'''
rep(oldind,newind)
rep("          A[row][row] -= (Ldt + dcr);\n          b[row] += -Ldt * iPrev;",
    "          A[row][row] -= (Leq + dcr);\n          b[row] += historyRhs;")

rep("        mosfetModel: solverOptions && solverOptions.mosfetModel === 'continuous' ? 'continuous' : 'simple',\n        linearSolver:",
    "        mosfetModel: solverOptions && solverOptions.mosfetModel === 'continuous' ? 'continuous' : 'simple',\n        integrationMethod,\n        linearSolver:")

rep("      inductors.forEach((ind, k) => {\n        const I = xSol[rowInd(k)] || 0;\n        indCurrent.set(ind.id, I);\n        this._indState.set(ind.id, I);\n      });",
    "      inductors.forEach((ind, k) => {\n        const I = xSol[rowInd(k)] || 0;\n        indCurrent.set(ind.id, I);\n        const oldI = this._indState.has(ind.id) ? this._indState.get(ind.id) : (Number.isFinite(Number(ind.initialCurrent)) ? Number(ind.initialCurrent) : 0);\n        if (this._indState.has(ind.id)) this._indPrevState.set(ind.id, oldI);\n        const va = voltages.get(uf.find(ind.a)) || 0;\n        const vb = voltages.get(uf.find(ind.b)) || 0;\n        this._indVoltageState.set(ind.id, (va - vb) - inductorDCR(ind.value) * I);\n        this._indState.set(ind.id, I);\n      });")

oldpost='''          const esr = capacitorESR(c);\n          const gC = 1 / (esr + Math.max(dt, 1e-12) / c.value);\n          const gLeak = 1 / capacitorLeakageR(c);\n          const vPrev = this._capState.has(c.id) ? this._capState.get(c.id) : capInitialV(c);\n          const capBranchI = gC * ((va - vb) - vPrev);\n          const leakI = gLeak * (va - vb);\n          I = capBranchI + leakI; // total current the part draws, ESR branch + leakage, same convention as every other component's a->b current\n          // ...and THAT current is what actually charges the ideal C this\n          // frame (real ESR drops some of (va-vb) across itself first;\n          // only the current through the ideal-C branch moves its charge)\n          this._capState.set(c.id, vPrev + (capBranchI * Math.max(dt, 1e-12)) / c.value);\n'''
newpost='''          const esr = capacitorESR(c);\n          const dtSafe = Math.max(dt, 1e-12);\n          const gLeak = 1 / capacitorLeakageR(c);\n          const vPrev = this._capState.has(c.id) ? this._capState.get(c.id) : capInitialV(c);\n          const hasPrev2 = this._capPrevState.has(c.id);\n          const useGear2 = integrationMethod === 'gear2' && hasPrev2;\n          const useTrap = integrationMethod === 'trapezoidal' && this._capCurrentState.has(c.id);\n          let idealG, historyCurrent;\n          if (useGear2) {\n            idealG = 3 * c.value / (2 * dtSafe);\n            historyCurrent = c.value * (4 * vPrev - this._capPrevState.get(c.id)) / (2 * dtSafe);\n          } else if (useTrap) {\n            idealG = 2 * c.value / dtSafe;\n            historyCurrent = idealG * vPrev + (this._capCurrentState.get(c.id) || 0);\n          } else {\n            idealG = c.value / dtSafe;\n            historyCurrent = idealG * vPrev;\n          }\n          const denom = 1 + idealG * esr;\n          const gC = idealG / denom;\n          const capBranchI = gC * (va - vb) - historyCurrent / denom;\n          const leakI = gLeak * (va - vb);\n          I = capBranchI + leakI;\n          const vCapNow = (va - vb) - esr * capBranchI;\n          if (this._capState.has(c.id)) this._capPrevState.set(c.id, vPrev);\n          this._capState.set(c.id, vCapNow);\n          this._capCurrentState.set(c.id, capBranchI);\n'''
rep(oldpost,newpost)
p.write_text(s)
