'use strict';
const test = require('node:test'), assert = require('node:assert/strict'), fs = require('node:fs'), vm = require('node:vm');
const K = require('./lattice-kernel.js');
const base = {frequencyHz: 1, coupling: 0, damping: 0, nonlinearity: 0};
const site = (x=0,v=0) => ({x,v,phase:0,n:[]});
function evolve(s,p,dt,n){for(let i=0;i<n;i++)s=K.advance(s,p,dt).sites;return s}
function geometry(){let s=[],map=new Map(),dirs=[[1,0],[1,-1],[0,-1],[-1,0],[-1,1],[0,1]];for(let q=-3;q<=3;q++)for(let r=Math.max(-3,-q-3);r<=Math.min(3,-q+3);r++){map.set(q+','+r,s.length);s.push({...site(),q,r})}s.forEach(a=>a.n=dirs.map(([q,r])=>map.get((a.q+q)+','+(a.r+r))).filter(i=>i!==undefined));return{s,map}}
test('zero state and phase convention preserved',()=>{const s=evolve([site()],base,.01,100);assert.equal(s[0].x,0);assert.equal(K.measure(s,base).phase_coherence,1)});
test('one safe step matches original kick then drift',()=>{let s=[site(1,.2)],dt=.01,w=2*Math.PI;let a=K.advance(s,base,dt);assert.equal(a.sites[0].v,.2-w*w*dt);assert.equal(a.sites[0].x,1+a.sites[0].v*dt);assert.equal(a.receipt.substeps,1);assert.deepEqual(s,[site(1,.2)])});
test('analytic oscillator converges under timestep refinement',()=>{function error(dt){let a=evolve([site(1)],base,dt,Math.round(.3/dt))[0];return Math.hypot(a.x-Math.cos(2*Math.PI*.3),a.v/(2*Math.PI)+Math.sin(2*Math.PI*.3))}assert.ok(error(.0025)<.55*error(.005))});
test('undamped numerical energy is bounded, not exact',()=>{let s=[site(1)],e0=K.measure(s,base).energy,max=0;for(let i=0;i<4000;i++){s=K.advance(s,base,.0025).sites;max=Math.max(max,Math.abs(K.measure(s,base).energy/e0-1))}assert.ok(max<.01)});
test('damped oscillator decays over time',()=>{let p={...base,damping:.1};let s=evolve([site(1)],p,.005,1000);assert.ok(K.measure(s,p).energy<.01*K.measure([site(1)],p).energy)});
test('allowed maximum frequency now uses internal substeps and remains finite',()=>{let p={...base,frequencyHz:9600},s=[site(1)];let a=K.advance(s,p,1/4096);assert.ok(a.receipt.substeps>=59);s=evolve(s,p,1/4096,512);assert.ok(Number.isFinite(K.measure(s,p).energy))});
test('invalid input and budget rejection leave caller untouched',()=>{let s=[site(1)],before=JSON.stringify(s);for(let p of [{...base,frequencyHz:NaN},{...base,coupling:-1}])assert.throws(()=>K.advance(s,p,.1),RangeError);assert.throws(()=>K.advance(s,base,Infinity),RangeError);assert.throws(()=>K.advance(s,base,1,[],{maxTrials:1}),RangeError);assert.throws(()=>K.advance(s,base,.1,[Infinity]),RangeError);assert.equal(JSON.stringify(s),before)});
test('nonlinear large drive adapts or atomically refuses',()=>{let s=[site()],before=JSON.stringify(s),p={...base,nonlinearity:2e6};let a=K.advance(s,p,.002,[1e6]);assert.ok(a.receipt.trials>a.receipt.substeps);assert.ok(Number.isFinite(K.measure(a.sites,p).energy));assert.equal(JSON.stringify(s),before);assert.throws(()=>K.advance(s,p,1,[1e100],{maxTrials:2}),RangeError);assert.equal(JSON.stringify(s),before)});
test('graph and forces rejected before evolution',()=>{assert.throws(()=>K.advance([{...site(),n:[1]},site()],base,.1),RangeError);assert.throws(()=>K.advance([site()],base,.1,[0,0]),RangeError)});
test('37-site geometry and actual GW sample replay stay finite and immutable',()=>{let{s,map}=geometry();assert.equal(s.length,37);assert.equal(s.reduce((a,x)=>a+x.n.length,0)/2,90);let data=JSON.parse(fs.readFileSync(__dirname+'/data/gw170817_v2_4khz_last2s.json'));let original=JSON.stringify(data);let p={frequencyHz:100,coupling:10000,damping:.01,nonlinearity:0};let peak=Math.max(...Object.values(data.detectors).flatMap(d=>d.values.map(Math.abs)));let ports={H1:map.get('3,0'),L1:map.get('-3,3'),V1:map.get('0,-3')};for(let k=0;k<64;k++){let force=s.map(()=>0);for(let d of ['H1','L1','V1'])force[ports[d]]+=data.detectors[d].values[k]/peak*250000;s=K.advance(s,p,1/data.window.sample_rate_hz,force).sites;}assert.ok(Number.isFinite(K.measure(s,p).energy));assert.equal(JSON.stringify(data),original)});
// Execute the actual inline UI script against a minimal DOM; browser pixels are a separate check.
function ui(){let html=fs.readFileSync(__dirname+'/index.html','utf8'),els={};for(let m of html.matchAll(/<(input|select|button|canvas|p|pre)[^>]*id="([^"]+)"[^>]*>/g)){let value=/value="([^"]*)"/.exec(m[0]);els[m[2]]={value:value?value[1]:'',textContent:'',addEventListener(type,fn){this[type]=fn}}}els.mode.value='all';els.c.width=760;els.c.height=620;els.c.getContext=()=>new Proxy({},{get:()=>()=>{}});els.c.getBoundingClientRect=()=>({left:0,top:0,width:760,height:620});let sandbox={document:{getElementById:id=>els[id]},performance:{now:()=>0},LatticeKernel:K,requestAnimationFrame(){},fetch:async()=>{throw Error('test fixture deliberately offline')},Math,console};vm.createContext(sandbox);vm.runInContext(html.match(/<script>\n([\s\S]*?)<\/script>/)[1],sandbox);return{els,sandbox,run:x=>vm.runInContext(x,sandbox)}}
test('actual UI binds default, pulse, frame, pause, reset and parameter reference',()=>{let u=ui();u.els.pulse.onclick();u.run('frame(16)');let out=JSON.parse(u.els.out.textContent);assert.ok(Number.isFinite(out.combined_state.energy));assert.equal(out.sites,37);u.els.toggle.onclick();assert.equal(u.run('running'),false);u.els.reset.onclick();assert.equal(u.run('steps'),0);u.els.freq.value='200';u.els.freq.input();assert.equal(u.run('energy0'),null)});
test('actual UI failure pauses and does not advance rejected replay sample',()=>{let u=ui();u.run("gw={window:{sample_rate_hz:4096,samples_per_detector:2,start_gps:0},detectors:{H1:{values:[0,0]},L1:{values:[0,0]},V1:{values:[0,0]}},source:{}};gwPeak=1;replaying=true");u.els.freq.value='NaN';u.run('frame(1)');assert.equal(u.run('sample'),0);assert.equal(u.run('running'),false);assert.match(u.els.solverStatus.textContent,/Paused safely/);u.els.freq.value='100';u.els.freq.input();u.els.reset.onclick();u.els.toggle.onclick();u.run('frame(2)');assert.equal(JSON.parse(u.els.out.textContent).solver_error,null)});

test('sparse force vectors are invalid rather than silently zero-filled',()=>{assert.throws(()=>K.advance([site()],base,.01,new Array(1)),RangeError)});
test('paused metrics failure is explicit and prevents drawing',()=>{let u=ui();u.els.toggle.onclick();u.els.freq.value='NaN';u.run('frame(1)');let o=JSON.parse(u.els.out.textContent);assert.match(o.solver_error,/frequencyHz/);assert.equal(o.combined_state.status,'unavailable');assert.match(u.els.solverStatus.textContent,/Paused safely/)});
