'use strict';
const $=id=>document.getElementById(id);
let timer, selected, busy=false, provider='AI';
const labels=['Checking reference','Choosing a bounded answer','Balancing sources','Drafting answer','Checking the differential','Retaining the result'];
async function api(path,data){const r=await fetch(path,data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{});const value=await r.json();if(!r.ok)throw new Error(value.error||'Connection unavailable');return value;}
function text(tag,content,parent){const e=document.createElement(tag);e.textContent=content;parent.append(e);return e;}
async function history(){const items=await api('/api/history');$('history').replaceChildren();for(const item of items){const b=text('button',item.question,$('history'));b.onclick=()=>show(item.id);}}
function render(item){$('welcome').hidden=true;$('result').hidden=false;$('question').textContent=item.question;$('answer').replaceChildren();$('sources').replaceChildren();$('checks').replaceChildren();$('status').textContent=item.status==='completed'?'Answer checked · saved':item.status==='paused'?'Paused · '+item.error:labels[item.cursor]+' · '+item.phase;
if(item.answer){const value=item.answer.answer;let at=0;for(const match of value.matchAll(/\[(S\d+)\]/g)){ $('answer').append(document.createTextNode(value.slice(at,match.index)));const source=item.sources.find(s=>s.id===match[1]);if(source){const a=text('a',match[0],$('answer'));a.href=source.url;a.target='_blank';a.rel='noopener noreferrer';}at=match.index+match[0].length;}$('answer').append(document.createTextNode(value.slice(at)));text('h2','Sources',$('sources'));const grid=document.createElement('div');grid.className='source-grid';$('sources').append(grid);for(const s of item.sources.filter(s=>item.answer.source_ids.includes(s.id))){const a=document.createElement('a');a.className='source-card';a.href=s.url;a.target='_blank';a.rel='noopener noreferrer';text('span',s.id+' · '+s.repo,a);text('strong',s.path.split('/').pop().replace(/_/g,' '),a);text('span',s.commit.slice(0,8)+' · lines '+s.start_line+'–'+s.end_line,a);grid.append(a);}if(item.answer.unresolved.length){text('h2','Still unresolved',$('sources'));text('p',item.answer.unresolved.join(' · '),$('sources'));}}
text('p','Evidence class: candidate interpretation. Repository statements retain their original status. Solver: NOT_RUN.',$('checks'));if(item.audit)text('p','Void: '+item.audit.decision+' — '+item.audit.summary+' (same provider model, separate audit pass).',$('checks'));text('p','Receipt: '+item.id,$('checks'));for(const ref of item.reference||[])text('p',ref.repo+' @ '+ref.commit+' · '+(ref.dirty?'dirty working tree excluded':'clean'),$('checks'));text('p','Coverage: configured repository roots only. Private Bench excluded. Nexus database and job board are not connected.',$('checks'));for(const e of item.events||[])text('div',e.step+' '+e.label+' / '+e.phase+' · '+(e.decision||'artifact stored'),$('checks'));
busy=item.status==='running';$('submit').disabled=busy;if(busy){timer=setTimeout(()=>show(item.id),1500);}else{history().catch(()=>{});}}
async function show(id){clearTimeout(timer);selected=id;try{render(await api('/api/conversation/'+encodeURIComponent(id)));}catch(e){$('status').textContent=e.message;}}
$('ask').onsubmit=async e=>{e.preventDefault();if(busy)return;const question=$('query').value.trim();if(!question)return;$('submit').disabled=true;try{const item=await api('/api/ask',{question,id:crypto.randomUUID()});$('query').value='';selected=item.id;render(item);}catch(error){$('health').textContent=error.message;$('submit').disabled=false;}};
$('query').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('ask').requestSubmit();}});
$('new').onclick=()=>{clearTimeout(timer);$('welcome').hidden=false;$('result').hidden=true;$('query').focus();};
for(const button of $('suggestions').children)button.onclick=()=>{$('query').value=button.textContent;$('ask').requestSubmit();};
$('journal').onclick=()=>$('correction-dialog').showModal();$('close-dialog').onclick=()=>$('correction-dialog').close();
$('correction').onsubmit=async e=>{e.preventDefault();try{await api('/api/correction',{text:$('correction-text').value});$('correction-text').value='';$('correction-dialog').close();$('health').textContent='Correction saved for future questions.';}catch(error){$('health').textContent=error.message;}};
api('/api/health').then(h=>{provider=h.provider;document.querySelector('#result>.eyebrow').textContent=provider.toUpperCase()+' · ONE-WAVE LENS';document.querySelector('.aside-bottom').replaceChildren(document.createTextNode(provider+' · personal workspace'));document.querySelector('.composer-bottom>span').textContent='◉ One-Wave lens · '+provider;$('health').textContent=(h.installed?h.route:provider+' not installed')+' · Repository sources · Nexus integration pending';}).catch(e=>{$('health').textContent=e.message;});history().catch(()=>{});
