(function () {
  'use strict';

  /*
   * Bench Reality UI
   * ----------------
   * The live app's green solver state is NOT a physical-bench approval.
   * This layer is deliberately conservative: unless the current circuit
   * matches a recognized physical bench profile, the UI says MODEL ONLY.
   *
   * Current strict profile:
   *   CELL_V1 dual +/-12 V supply, one real shared 0 midpoint, <=20 mA,
   *   no vgnd/TLE helper on top of that midpoint, and a solid low-ohm 0
   *   spine between the supply midpoint and a balanced/lean resistor cell.
   *
   * PHYSICAL PASS can never be generated by software. That label requires
   * an actual meter/scope receipt from the real board.
   */

  const LIMIT_A = 0.020;
  const LOW_OHM = 0.25;
  const I0_ZERO_A = 50e-6;
  const ACTIVE_POWER_W = 1e-6;
  const ACTIVE_CURRENT_A = 1e-6;

  function installStyle() {
    const style = document.createElement('style');
    style.textContent = `
      #warnings .ok { display:none !important; }
      #benchRealityPanel { display:flex; flex-direction:column; gap:3px; max-width:min(760px,70vw); font-size:12px; }
      #benchRealityTop { display:flex; gap:7px; align-items:center; flex-wrap:wrap; }
      .bench-chip { font-weight:800; letter-spacing:.03em; border-radius:4px; padding:2px 7px; border:1px solid currentColor; }
      .bench-model { color:#d8a225; }
      .bench-pass { color:#2fa968; }
      .bench-fail { color:#e25252; }
      .bench-physical { color:#aaa; }
      #benchRealityDetail { color:#c9d3df; }
      #benchRealityErrors { color:#ff7777; }
    `;
    document.head.appendChild(style);
  }

  function installPanel() {
    const footer = document.querySelector('.status-bar');
    if (!footer || document.getElementById('benchRealityPanel')) return;
    const panel = document.createElement('div');
    panel.id = 'benchRealityPanel';
    panel.innerHTML = `
      <div id="benchRealityTop">
        <span id="benchRealityChip" class="bench-chip bench-model">MODEL ONLY</span>
        <span class="bench-chip bench-physical">PHYSICAL PASS: NOT MEASURED</span>
      </div>
      <div id="benchRealityDetail">Solver/model output is not automatically a breadboard pass.</div>
      <div id="benchRealityErrors"></div>
    `;
    footer.appendChild(panel);
  }

  function uf() {
    const parent = new Map();
    function find(x) {
      if (!parent.has(x)) parent.set(x, x);
      const p = parent.get(x);
      if (p === x) return x;
      const r = find(p);
      parent.set(x, r);
      return r;
    }
    function union(a, b) {
      const ra = find(a), rb = find(b);
      if (ra !== rb) parent.set(ra, rb);
    }
    return { find, union, parent };
  }

  function tnode(p, i) {
    return p && p.terminals && p.terminals[i] ? p.terminals[i].cellId : null;
  }

  function voltage(node) {
    if (!node || typeof window.__nodeVoltage !== 'function') return NaN;
    const v = window.__nodeVoltage(node);
    return Number.isFinite(v) ? v : NaN;
  }

  function current(debug, id) {
    const v = debug && debug.currents ? debug.currents[id] : undefined;
    return Number.isFinite(v) ? v : NaN;
  }

  function physicalNets(parts) {
    const u = uf();
    parts.forEach((p) => {
      (p.terminals || []).forEach((t) => u.find(t.cellId));
      if (p.type === 'wire') {
        u.union(tnode(p, 0), tnode(p, 1));
      } else if (p.type === 'ywire' && p.terminals.length >= 4) {
        u.union(tnode(p, 0), tnode(p, 1));
        u.union(tnode(p, 0), tnode(p, 2));
        u.union(tnode(p, 2), tnode(p, 3));
      } else if (p.type === 'resistor' && p.value > 0 && p.value <= LOW_OHM) {
        u.union(tnode(p, 0), tnode(p, 1));
      } else if ((p.type === 'switch' || p.type === 'pushbutton') && p.closed) {
        u.union(tnode(p, 0), tnode(p, 1));
      }
    });
    return u;
  }

  function findDual12(parts) {
    const bats = parts.filter((p) => p.type === 'battery' && Math.abs((p.value || 0) - 12) <= 0.75);
    for (let i = 0; i < bats.length; i++) {
      for (let j = i + 1; j < bats.length; j++) {
        const a = [tnode(bats[i], 0), tnode(bats[i], 1)];
        const b = [tnode(bats[j], 0), tnode(bats[j], 1)];
        for (const shared of a) {
          if (shared && b.includes(shared)) {
            const outerA = a.find((n) => n !== shared);
            const outerB = b.find((n) => n !== shared);
            if (outerA && outerB) return { positive: bats[i], negative: bats[j], center: shared, outerA, outerB };
          }
        }
      }
    }
    return null;
  }

  function resistorPower(debug, parts) {
    let p = 0;
    parts.filter((x) => x.type === 'resistor' && x.value > 0).forEach((r) => {
      const i = current(debug, r.id);
      if (Number.isFinite(i)) p += i * i * r.value;
    });
    return p;
  }

  function findCenterCell(parts, dual, nets) {
    const centerRoot = nets.find(dual.center);
    const resistors = parts.filter((p) => p.type === 'resistor' && p.value > LOW_OHM);
    for (const r1 of resistors) {
      for (const r2 of resistors) {
        if (r1 === r2) continue;
        const r1a = nets.find(tnode(r1, 0)), r1b = nets.find(tnode(r1, 1));
        const r2a = nets.find(tnode(r2, 0)), r2b = nets.find(tnode(r2, 1));
        const pRoot = nets.find(dual.outerA), nRoot = nets.find(dual.outerB);
        let mid1 = null;
        if (r1a === pRoot) mid1 = r1b;
        else if (r1b === pRoot) mid1 = r1a;
        if (!mid1) continue;
        let mid2 = null;
        if (r2a === nRoot) mid2 = r2b;
        else if (r2b === nRoot) mid2 = r2a;
        if (mid1 && mid2 && mid1 === mid2) {
          return { root: mid1, centerRoot, upper: r1, lower: r2 };
        }
      }
    }
    return null;
  }

  function directCenterCap(parts, dual, nets) {
    const centerRoot = nets.find(dual.center);
    return parts.find((p) => {
      if (p.type !== 'capacitor') return false;
      const a = nets.find(tnode(p, 0)), b = nets.find(tnode(p, 1));
      return a === centerRoot || b === centerRoot;
    });
  }

  function centerShunt(parts, dual) {
    const center = dual.center;
    return parts.find((p) => p.type === 'resistor' && p.value > 0 && p.value <= LOW_OHM && (tnode(p, 0) === center || tnode(p, 1) === center));
  }

  function audit(debug) {
    const parts = debug.parts || [];
    const errors = [];
    const notes = [];
    const dual = findDual12(parts);

    if (!dual) {
      return {
        state: 'model',
        title: 'MODEL ONLY',
        detail: 'No recognized ±12 V CELL_V1 dual-supply profile. Numerical results are not a physical pass.',
        errors: [],
      };
    }

    const nets = physicalNets(parts);
    const cell = findCenterCell(parts, dual, nets);
    const vgnds = parts.filter((p) => p.type === 'vgnd');
    if (vgnds.length) errors.push('Dual ±12 V midpoint + virtual-ground/TLE helper are mixed. Remove the synthetic midpoint.');

    const iPos = current(debug, dual.positive.id);
    const iNeg = current(debug, dual.negative.id);
    for (const [name, value] of [['+ supply', iPos], ['− supply', iNeg]]) {
      if (!Number.isFinite(value)) errors.push(`${name}: no current receipt.`);
      else if (Math.abs(value) > LIMIT_A) errors.push(`${name}: ${Math.abs(value * 1000).toFixed(2)} mA exceeds 20 mA bench limit.`);
    }

    const loadP = resistorPower(debug, parts);
    const sourceMax = Math.max(Number.isFinite(iPos) ? Math.abs(iPos) : 0, Number.isFinite(iNeg) ? Math.abs(iNeg) : 0);
    if (loadP > ACTIVE_POWER_W && sourceMax < ACTIVE_CURRENT_A) {
      errors.push(`Active load dissipates ${(loadP * 1000).toFixed(3)} mW but source receipt is effectively 0 A.`);
    }

    if (!cell) {
      errors.push('No valid +rail → resistor → local midpoint → resistor → −rail CELL_V1 baseline found.');
    } else {
      const centerSolid = cell.root === cell.centerRoot;
      if (!centerSolid) {
        const cap = directCenterCap(parts, dual, nets);
        errors.push(cap
          ? '0/CENTER is not DC-solid: a capacitor touches the supply midpoint but does not make a DC spine.'
          : 'Local cell midpoint is not solidly bonded to the real supply 0/CENTER.');
      }
      const shunt = centerShunt(parts, dual);
      if (shunt) {
        const i0 = current(debug, shunt.id);
        const ru = cell.upper.value, rl = cell.lower.value;
        if (!Number.isFinite(i0)) {
          errors.push('I₀ shunt exists but has no solved current receipt.');
        } else {
          notes.push(`I₀ receipt ${(i0 * 1000).toFixed(3)} mA through ${shunt.value} Ω.`);
          const matched = Math.abs(ru - rl) / Math.max(ru, rl) < 0.01;
          if (matched && Math.abs(i0) > I0_ZERO_A) errors.push(`Equal arms but I₀=${(i0 * 1000).toFixed(3)} mA; expected approximately zero.`);
          if (!matched && Math.abs(i0) <= I0_ZERO_A) errors.push(`Arms are unequal (${ru} Ω / ${rl} Ω) but I₀ did not take a measurable sign.`);
        }
      } else {
        errors.push('No ≤0.25 Ω I₀ shunt/current-sense path at the supply 0/CENTER. Required receipt is missing.');
      }
    }

    parts.filter((p) => p.type === 'nmos').forEach((q) => {
      const vg = voltage(tnode(q, 0));
      const vd = voltage(tnode(q, 1));
      const vs = voltage(tnode(q, 2));
      const vgs = vg - vs;
      const threshold = Number.isFinite(q.value) ? q.value : 1.5;
      const centerV = voltage(dual.center);
      if ([vg, vd, vs, centerV].every(Number.isFinite) && vs > centerV + 1 && vd > vs + 2 && vgs < threshold) {
        errors.push(`${q.id}: high-side N-MOS has only VGS=${vgs.toFixed(2)} V at elevated source; GPIO-style drive cannot turn it on.`);
      }
    });

    return {
      state: errors.length ? 'fail' : 'pass',
      title: errors.length ? 'BENCH REALITY FAIL' : 'BENCH REALITY PASS',
      detail: errors.length
        ? 'Solver output exists, but this circuit does not meet the current physical CELL_V1 contract.'
        : `±12 V CELL_V1 profile matches; source currents are within 20 mA, 0/CENTER is solid, and the required I₀ receipt exists. ${notes.join(' ')}`,
      errors,
    };
  }

  function render() {
    if (typeof window.__debugState !== 'function') return;
    installPanel();
    const debug = window.__debugState();
    const result = audit(debug);
    const chip = document.getElementById('benchRealityChip');
    const detail = document.getElementById('benchRealityDetail');
    const errs = document.getElementById('benchRealityErrors');
    if (!chip || !detail || !errs) return;
    chip.textContent = result.title;
    chip.className = 'bench-chip ' + (result.state === 'pass' ? 'bench-pass' : result.state === 'fail' ? 'bench-fail' : 'bench-model');
    detail.textContent = result.detail;
    errs.innerHTML = result.errors.map((e) => `✖ ${escapeHtml(e)}`).join('<br>');
  }

  function escapeHtml(s) {
    return String(s).replace(/[&<>]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c]));
  }

  installStyle();
  installPanel();
  setInterval(render, 120);
})();
